---
name: KygekRanksUI
version: 1.0.0
main: Kygekraqmak\KygekRanksUI\Main
api: 3.0.0
author: Kygekraqmak

commands:
  ranks:
    description: Information about ranks in the server
    permission: kygekranksui.ranks
    usage: "/ranks"

permissions:
  kygekranksui.ranks:
    description: Permission to use /ranks command
    default: true
...
